<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="robots" content="index, follow">
		<title>Status</title>
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.css">
		<link rel="stylesheet" href="milligram.min.css">
		<link rel="stylesheet" href="style.css">
		
		<link rel="icon" href="https://raw.githubusercontent.com/pyupio/statuspage/master/template/favicon.png">
	</head>
	<body>

		<main class="wrapper">

			<nav class="navigation">
				<section class="container">

					<a class="navigation-title" href="">
						
						<img class="img" src="https://raw.githubusercontent.com/pyupio/statuspage/master/template/logo.png" height="30">
						<h1 class="title">Status</h1>
					</a>



				</section>
			</nav>

			<section class="container" id="main">
				
					
					<div class="panel degraded performance">
						Degraded performance on Anaconda.org, AppVeyor.
					</div>
					
				

				<h4>Systems</h4>
				<ul class="systems">
					
					<li>
						Anaconda.org <span class="status degraded performance">degraded performance</span>
					</li>
					
					<li>
						AppVeyor <span class="status degraded performance">degraded performance</span>
					</li>
					
					<li>
						CircleCI <span class="status operational">operational</span>
					</li>
					
					<li>
						Travis CI <span class="status operational">operational</span>
					</li>
					
					<li>
						conda <span class="status operational">operational</span>
					</li>
					
					<li>
						docs <span class="status operational">operational</span>
					</li>
					
					<li>
						feedstocks <span class="status operational">operational</span>
					</li>
					
					<li>
						linter <span class="status operational">operational</span>
					</li>
					
					<li>
						staged-recipes <span class="status operational">operational</span>
					</li>
					
				</ul>

				<h4>Incidents</h4>
				
					
					<div class="incident">
						<span class="date">2016-08-18 23:43:30 UTC</span>

						
							<span class="label degraded performance float-right">degraded performance</span>
						
						
							<span class="label system float-right">Anaconda.org</span>
						
							<span class="label system float-right">AppVeyor</span>
						
						<hr/>

						<span class="title">Issues uploading on AppVeyor</span>
						<p>It appears there are some issues uploading from AppVeyor to anaconda.org. Here is a [log]( https://ci.appveyor.com/project/conda-forge/hdbscan-feedstock/build/1.0.10/job/ljwl03dcll9xitqy#L449 ) from one such failed AppVeyor upload failure. Snippet of traceback shown below. Restarting seems to sometimes fix it.

```
python ci_support\upload_or_check_non_existence.py .\recipe conda-forge --channel=main
Using Anaconda API: https://api.anaconda.org
Traceback (most recent call last):
  File "ci_support\upload_or_check_non_existence.py", line 124, in <module>
    main()
  File "ci_support\upload_or_check_non_existence.py", line 106, in main
    on_channel = distribution_exists_on_channel(cli, meta, owner, channel)
  File "ci_support\upload_or_check_non_existence.py", line 69, in distribution_exists_on_channel
    binstar_cli.show_channel(owner=owner, channel=channel)['files']]
  File "C:\conda\lib\site-packages\binstar_client\mixins\channels.py", line 29, in show_channel
    self._check_response(res, [200])
  File "C:\conda\lib\site-packages\binstar_client\__init__.py", line 200, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.NotFound: ('Not Found: Nothing matches the given URI ([GET] https://api.anaconda.org/channels/conda-forge/main -> 404)', 404)
Command exited with code 1
```

cc @msarahan @mcg1969</p>
						
							<p><em>Update 2016-08-18 23:50:23</em><br/>
							Raising for awareness of affected teams/feedstocks that have tried to deploy recently and are now having deployment issues. Feel free to track an issue locally on your feedstock until all missing packages are uploaded.

cc @conda-forge/bqplot @conda-forge/requests-futures @conda-forge/hdbscan @conda-forge/versioneer
							</p>
						
							<p><em>Update 2016-08-18 23:58:53</em><br/>
							Restarted builds for the apparently affected feedstocks. Seems to be localized to very recent updates or new feedstocks.
							</p>
						
					</div>
					
					<div class="incident">
						<span class="date">2016-08-18 19:26:48 UTC</span>

						
							<span class="label operational float-right">resolved</span>
						
						
							<span class="label system float-right">staged-recipes</span>
						
						<hr/>

						<span class="title">Conversion failure</span>
						<p>Appears there is some issue be encountered during conversion. May be related to the recent `conda-build` upgrade.

Traceback shown below. See this [log]( https://travis-ci.org/conda-forge/staged-recipes/jobs/153361154 ) for more details.

```
Calculating the recipes which need to be turned into feedstocks.
Making feedstock for versioneer
Traceback (most recent call last):
  File "/Users/travis/miniconda/bin/conda-smithy", line 9, in <module>
    load_entry_point('conda-smithy==1.0.3', 'console_scripts', 'conda-smithy')()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 236, in main
    args.subcommand_func(args)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 103, in __call__
    generate_feedstock_content(feedstock_directory, args.recipe_directory, meta)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 34, in generate_feedstock_content
    configure_feedstock.main(target_directory)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 361, in main
    render_run_docker_build(env, config, forge_dir)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 24, in render_run_docker_build
    with fudge_subdir('linux-64'):
  File "/Users/travis/miniconda/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 103, in fudge_subdir
    orig = conda_build.metadata.cc.subdir
AttributeError: module 'conda_build.metadata' has no attribute 'cc'
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 150, in <module>
    '--feedstock-directory', feedstock_dir])
  File "/Users/travis/miniconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'init', '/Users/travis/build/conda-forge/staged-recipes/recipes/versioneer', '--feedstock-directory', '/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmpx54jano2__feedstocks/versioneer-feedstock']' returned non-zero exit status 1
```

cc @patricksnape @msarahan @pelson</p>
						
							<p><em>Update 2016-08-18 19:28:42</em><br/>
							Happened in the subsequent [build]( https://travis-ci.org/conda-forge/staged-recipes/builds/153362768 ) too. May be worthwhile to pin `conda-build` to the last known working version (`1.21.11`) in the feedstock conversion script for now. Not sure if this is also related to `conda-build-all` or `conda-smithy`.
							</p>
						
							<p><em>Update 2016-08-18 19:33:27</em><br/>
							Adding PR ( https://github.com/conda-forge/staged-recipes/pull/1293 ) to workaround this issue for the meantime.
							</p>
						
							<p><em>Update 2016-08-18 19:54:51</em><br/>
							Resolved via pinning of `conda-build` to version `1.21.11` for feedstock conversion via PR ( https://github.com/conda-forge/staged-recipes/pull/1293 ).
							</p>
						
					</div>
					
					<div class="incident">
						<span class="date">2016-08-14 19:43:20 UTC</span>

						
							<span class="label operational float-right">resolved</span>
						
						
							<span class="label system float-right">docs</span>
						
						<hr/>

						<span class="title">Testing...</span>
						<p>Just testing please ignore and unsubscribe.</p>
						
							<p><em>Update 2016-08-14 19:43:48</em><br/>
							Testing completed.
							</p>
						
							<p><em>Update 2016-08-17 14:54:05</em><br/>
							Reopening for testing.
							</p>
						
					</div>
					
				
			</section>


			<footer class="footer">
				<section class="container">
					<hr/>
					
					<p>Status page hosted by GitHub, generated with <a href="https://github.com/pyupio/statuspage">pyupio/statuspage</a></p>
				</section>
			</footer>

		</main>

	</body>
</html>